version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: medical-api-db
    environment:
      POSTGRES_USER: medical_user
      POSTGRES_PASSWORD: medical_password
      POSTGRES_DB: medical_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: